# Dev build: expects pre-built binary at bin/envoy
ARG BASE_TAG=latest
FROM protectorate/base:${BASE_TAG}

COPY bin/envoy /usr/local/bin/envoy
COPY configs/envoy.yaml /etc/envoy/envoy.yaml
COPY containers/envoy/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 7470

ENTRYPOINT ["/entrypoint.sh"]
